services:
  backend:
    build:
      context: ./backend
    container_name: rj_dental_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: rj_dental_frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:14-alpine
    container_name: rj_dental_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: rj_dental_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: